import categories_topological_spaces_continuous_mappings_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace categories_topological_spaces_continuous_mappings_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end categories_topological_spaces_continuous_mappings_foundation_canonical_lane_mathlib
end HautevilleHouse
